[default]
workers = 8
max_blocking = 64
ident = "Tappd Server"
temp_dir = "/tmp"
keep_alive = 10
log_level = "debug"

[default.core]
app_name = ""
keys_file = "/tapp/.host-shared/.appkeys.json"
compose_file = "/tapp/.host-shared/app-compose.json"
public_logs = true
public_sysinfo = true

[internal]
address = "unix:/var/run/tappd.sock"
reuse = true

[external]
address = "0.0.0.0"
port = 8090

[guest-api]
address = "vsock:0xffffffff"
port = 8000
