x-build-context: &build-context
  context: .
  dockerfile_inline: |
    FROM rust:1.84@sha256:738ae99a3d75623f41e6882566b4ef37e38a9840244a47efd4a0ca22e9628b88
    WORKDIR /app
    RUN apt-get update && apt-get install -y git build-essential libssl-dev protobuf-compiler libprotobuf-dev wireguard-tools iproute2 libclang-dev
    RUN git clone https://github.com/Dstack-TEE/dstack.git && \
        cd dstack && \
        git checkout 3a63e95
    WORKDIR /app/dstack/tproxy/tapp
    RUN apt-get install -y jq
    RUN cargo build --release -p certbot-cli -p tproxy
    COPY *.sh /app/dstack/tproxy/tapp/

services:
  tproxy:
    build: *build-context
    entrypoint:
      - /app/dstack/tproxy/tapp/tproxy-entrypoint.sh
    command: ["/app/dstack/target/release/tproxy", "-c", "/etc/tproxy/tproxy.toml"]
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - tproxy-volume:/data
      - tproxy-conf:/etc/tproxy
      - rproxy-conf:/etc/rproxy
      - /tapp:/tapp
    network_mode: host
    privileged: true
    environment:
      - WG_ENDPOINT=${WG_ENDPOINT}
      - SRV_DOMAIN=${SRV_DOMAIN}
    restart: always
    depends_on:
      - certbot-bootstrap

  certbot-bootstrap:
    build: *build-context
    entrypoint:
      - /app/dstack/tproxy/tapp/certbot-entrypoint.sh
    command: ["/app/dstack/target/release/certbot", "renew", "--once", "-c", "/etc/certbot/certbot.toml"]
    volumes:
      - rproxy-conf:/etc/rproxy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - SRV_DOMAIN=${SRV_DOMAIN}
    network_mode: host
    restart: on-failure

  certbot-renew:
    build: *build-context
    entrypoint:
      - /app/dstack/tproxy/tapp/certbot-entrypoint.sh
    command: ["/app/dstack/target/release/certbot", "renew", "-c", "/etc/certbot/certbot.toml"]
    volumes:
      - rproxy-conf:/etc/rproxy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - SRV_DOMAIN=${SRV_DOMAIN}
    network_mode: host
    restart: always
    depends_on:
      - certbot-bootstrap

volumes:
  tproxy-volume:
  tproxy-conf:
  rproxy-conf: