services:
  tproxy:
    image: tproxy-built
    entrypoint:
      - /app/dstack/tproxy/tapp/tproxy-entrypoint.sh
    command: ["/app/dstack/target/release/tproxy", "-c", "/etc/tproxy/tproxy.toml"]
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - tproxy-volume:/data
      - tproxy-conf:/etc/tproxy
      - rproxy-conf:/etc/rproxy
      - build:/tapp
    network_mode: host
    privileged: true
    environment:
      - WG_ENDPOINT=${WG_ENDPOINT}
      - SRV_DOMAIN=${SRV_DOMAIN}
    restart: always
    depends_on:
      - certbot-bootstrap
  certbot-bootstrap:
    image: tproxy-built
    entrypoint:
      - /app/dstack/tproxy/tapp/certbot-entrypoint.sh
    command: ["/app/dstack/target/release/certbot", "renew", "--once", "-c", "/etc/certbot/certbot.toml"]
    volumes:
      - rproxy-conf:/etc/rproxy
      - build:/tapp
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - SRV_DOMAIN=${SRV_DOMAIN}
    network_mode: host
    restart: never
    depends_on:
      - builder
  certbot-renew:
    image: tproxy-built
    entrypoint:
      - /app/dstack/tproxy/tapp/certbot-entrypoint.sh
    command: ["/app/dstack/target/release/certbot", "renew", "-c", "/etc/certbot/certbot.toml"]
    volumes:
      - rproxy-conf:/etc/rproxy
      - build:/tapp
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - SRV_DOMAIN=${SRV_DOMAIN}
    network_mode: host
    restart: always
    depends_on:
      - certbot-bootstrap
  builder:
    build:
      context: .
      dockerfile_inline: |
        FROM rust:1.84
        WORKDIR /app
        RUN apt-get update && apt-get install -y git build-essential libssl-dev protobuf-compiler libprotobuf-dev wireguard-tools iproute2 libclang-dev
        RUN git clone https://github.com/Dstack-TEE/dstack.git && \
            cd dstack && \
            git checkout afc0824
        WORKDIR /app/dstack/tproxy/tapp
        RUN cargo build --release -p certbot-cli -p tproxy
    restart: never
    image: tproxy-built
    volumes:
      - build:/tapp

volumes:
  build:
  tproxy-volume:
  tproxy-conf:
  rproxy-conf: