services:
  gramine-sealing-key-provider:
    container_name: gramine-sealing-key-provider
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    volumes:
      - "/etc/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf"
    environment:
      - SGX=1 
    ports:
      - "3443:3443"
