[default]
workers = 8
max_blocking = 64
ident = "Phala KMS"
temp_dir = "/tmp"
keep_alive = 10
log_level = "info"

[rpc]
address = "0.0.0.0"
port = 8000

[rpc.tls]
key = "/etc/kms/certs/rpc.key"
certs = "/etc/kms/certs/rpc.cert"

[rpc.tls.mutual]
ca_certs = "/etc/kms/certs/tmp-ca.cert"
mandatory = false

[core]
root_ca_cert = "/etc/kms/certs/ca.cert"
root_ca_key = "/etc/kms/certs/ca.key"
tmp_ca_cert = "/etc/kms/certs/tmp-ca.cert"
tmp_ca_key = "/etc/kms/certs/tmp-ca.key"
rpc_cert = "/etc/kms/certs/rpc.cert"
rpc_key = "/etc/kms/certs/rpc.key"
k256_key = "/etc/kms/certs/root-k256.key"
subject_postfix = ".dstack"
pccs_url = "https://api.trustedservices.intel.com/tdx/certification/v4"

[core.auth_api]
# "dev" for local testing
# "webhook" for production
type = "webhook"
url = "http://auth-api:8000"

[core.onboard]
enabled = true
quote_enabled = true
address = "0.0.0.0"
port = 8000
