name: Rust checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.84.1
      with:
        components: clippy, rustfmt
    
    - name: Run Clippy
      run: cargo clippy -- -D warnings --allow unused_variables 
    
    - name: Cargo fmt check
      run: cargo fmt --check --all

    - name: Run tests
      run: cargo test